import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { MapHeader } from "@/components/MapHeader";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>MUNDO Maps - Maps for Model UN DevOps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/unopengis_logo.png" />
      </Head>
      <main className={styles.main}>
        <MapHeader />
        <h1 className={`${inter.className} ${styles.header}`}>
          MUNDO Maps - Maps for Model UN DevOps
        </h1>
        <div className={styles.missions}>
          <h2 className={inter.className}>Select mission</h2>
          <ul className={styles.list}>
            <li>
              <Link href="/missions/Taito-ku">Taito-ku (demo)</Link>
            </li>
            <li>
              <Link href="/missions/UNMISS">UNMISS</Link>
            </li>
            <li>
              <Link href="/missions/UNMIK">UNMIK</Link>
            </li>
          </ul>
        </div>
      </main>
    </>
  );
}
